/**:
  controller_manager:
    ros__parameters:

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
        state: active

      dynaarm_status_broadcaster:
        type: duatic_dynaarm_controllers/StatusBroadcaster
        state: active

      gravity_compensation_controller:
        type: duatic_dynaarm_controllers/GravityCompensationController
        state: active

      freedrive_controller:
        type: duatic_dynaarm_controllers/FreeDriveController
        state: inactive

      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController
        state: inactive

      cartesian_pose_controller:
        type: duatic_dynaarm_controllers/CartesianPoseController
        state: inactive

      freeze_controller:
        type: duatic_dynaarm_controllers/FreezeController
        state: active

      virtual_fts:
        type: duatic_dynaarm_controllers/ForceTorqueBroadcaster
        state: active

/**/joint_state_broadcaster:
  ros__parameters:
    use_urdf_to_filter: false
    joints:
      - shoulder_rotation
      - shoulder_flexion
      - elbow_flexion
      - forearm_rotation
      - wrist_flexion
      - wrist_rotation

/**/dynaarm_status_broadcaster:
  ros__parameters:
    joints:
      - shoulder_rotation
      - shoulder_flexion
      - elbow_flexion
      - forearm_rotation
      - wrist_flexion
      - wrist_rotation

/**/virtual_fts:
  ros__parameters:
    joints:
      - shoulder_rotation
      - shoulder_flexion
      - elbow_flexion
      - forearm_rotation
      - wrist_flexion
      - wrist_rotation
    endeffector_frame: "flange"
    use_svd_solver: true

/**/joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_rotation
      - shoulder_flexion
      - elbow_flexion
      - forearm_rotation
      - wrist_flexion
      - wrist_rotation
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    # See https://control.ros.org/jazzy/doc/ros2_controllers/joint_trajectory_controller/doc/parameters.html for a full list of all parameters
    allow_partial_joints_goal: false # trajectory needs to contains goals from all joints handled by the controller
    allow_nonzero_velocity_at_trajectory_end: true
    # set_last_command_interface_value_as_state_on_activation: false
    constraints:
      stopped_velocity_tolerance: 0.5
      goal_time: 0.05
      # Tolerances for each joint
      shoulder_rotation: { trajectory: 0.5, goal: 0.05 }
      shoulder_flexion: { trajectory: 0.5, goal: 0.05 }
      elbow_flexion: { trajectory: 0.5, goal: 0.05 }
      forearm_rotation: { trajectory: 0.5, goal: 0.05 }
      wrist_flexion: { trajectory: 0.5, goal: 0.05 }
      wrist_rotation: { trajectory: 0.5, goal: 0.05 }

/**/gravity_compensation_controller:
  ros__parameters:
    joints:
      - shoulder_rotation
      - shoulder_flexion
      - elbow_flexion
      - forearm_rotation
      - wrist_flexion
      - wrist_rotation

/**/freedrive_controller:
  ros__parameters:
    joints:
      - shoulder_rotation
      - shoulder_flexion
      - elbow_flexion
      - forearm_rotation
      - wrist_flexion
      - wrist_rotation

/**/freeze_controller:
  ros__parameters:
    names:
      - DynaarmSystem

/**/cartesian_pose_controller:
  ros__parameters:
    joints:
      - shoulder_rotation
      - shoulder_flexion
      - elbow_flexion
      - forearm_rotation
      - wrist_flexion
      - wrist_rotation
    command_interfaces:
      - position
      - velocity
      - acceleration_commanded
    srdf: <srdf>
    end_effector_frame: "flange"
